name: Export
on:
  workflow_dispatch:
jobs:
  export:
    runs-on: windows-latest
    environment: 
        name: 'Development'
    steps:
      - uses: actions/checkout@v3
      - name: who-am-i action
        uses: microsoft/powerplatform-actions/who-am-i@v0.6.3
        with:
            environment-url: ${{ secrets.ENVIRONMENT_URL }}
            app-id: ${{ secrets.POWERPLATFORM_APPID }}
            client-secret: ${{ secrets.POWERPLATFORM_CLIENTSECRET }}
            tenant-id: ${{ secrets.TENANT_ID }}
      - name: export-solution action
        uses: microsoft/powerplatform-actions/export-solution@v0.6.3
        with:
            managed: false
            environment-url: ${{ secrets.ENVIRONMENT_URL }}
            app-id: ${{ secrets.POWERPLATFORM_APPID }}
            client-secret: ${{ secrets.POWERPLATFORM_CLIENTSECRET }}
            tenant-id: ${{ secrets.TENANT_ID }}
            solution-name: ${{ secrets.SOLUTION_NAME }}
            solution-output-file: bin/${{ secrets.SOLUTION_NAME }}.zip
